// SPDX-License-Identifier: LGPL-3.0-or-later
pragma solidity ^0.8.9;

import { ILootContainer } from "./interfaces/ILootContainer.sol";
import { LootItem } from "./LootItem.sol";

/// @author 0xBlackbeard
contract LootWeapon is LootItem {
	constructor() LootItem("Programmable Loot [Weapon]", "pLOOT/WEAPON") {
		items = [
			"Axe",
			"Bardiche",
			"Baton",
			"Battle axe",
			"Bazooka",
			"Bill",
			"Blowgun",
			"Bludgeon",
			"Blunderbuss",
			"Boar-spear",
			"Bokken",
			"Bolo",
			"Bow",
			"Brass knuckles",
			"Bullwhip",
			"Changdao",
			"Cheiroballistra",
			"Cinquedea",
			"Claymore",
			"Club",
			"Colichemarde",
			"Coronation sword",
			"Crossbow",
			"Curved bow",
			"Cutlass",
			"Dagger",
			"Dagger-axe",
			"Doloire",
			"Eku",
			"Falchion",
			"Falx",
			"Firearm",
			"Flail",
			"Flamberge",
			"Flanged mace",
			"Flyssa",
			"Gastraphetes",
			"Gladius",
			"Greek fire",
			"Gun",
			"Hakapik",
			"Halberd",
			"Hammer",
			"Hand cannon",
			"Harpe",
			"Harpoon",
			"Hasta",
			"Hatchet",
			"Hoko yari",
			"Hunga munga",
			"Hunting spear",
			"Hunting sword",
			"Ida",
			"Jangchang",
			"Javelin",
			"Jingal",
			"Katana",
			"Kestros",
			"Knife",
			"Kopis",
			"Labrys",
			"Lasso",
			"Lathi",
			"Longbow",
			"Longsword",
			"Luwuk",
			"Macana",
			"Mace",
			"Machete",
			"Makhaira",
			"Mallet",
			"Masakari",
			"Mattock",
			"Maul",
			"Mere",
			"Mesangylon",
			"Miao dao",
			"Moplah",
			"Morning star",
			"Musket",
			"Pernach",
			"Petronel",
			"Pickaxe",
			"Pike",
			"Pilum",
			"Pistol",
			"Pitchfork",
			"Polearm",
			"Poleaxe",
			"Pudao",
			"Quarterstaff",
			"Rapier",
			"Repeating crossbow",
			"Ribauldequin",
			"Rifle",
			"Rock",
			"Saber",
			"Sagaris",
			"Sarissa",
			"Sasumata",
			"Scimitar",
			"Shillelagh",
			"Sniper rifle",
			"Shortsword",
			"Sibat",
			"Sickle",
			"Sledgehammer",
			"Sling",
			"Soliferrum",
			"Spadroon",
			"Spatha",
			"Spear",
			"Stave",
			"Stick",
			"Stone",
			"Suburito",
			"Sword",
			"Swordstaff",
			"Tabarzin",
			"Tachi",
			"Tekkan",
			"Tomahawk",
			"Trident",
			"Tuck",
			"Uchigatana",
			"Ulfberht",
			"Vel",
			"Verutum",
			"Wand",
			"Warhammer",
			"Wodao",
			"Wrench",
			"Xiphos"
		];
	}

	/**
	 * @dev See {LootContainer-mintItem}.
	 */
	function mint(
		address to,
		ILootContainer.Containers container,
		uint256 seed
	) external override onlyOwner {
		mintItem(to, container, Items.WEAPON, seed);
	}

	/**
	 * @dev See {LootContainer-tokenURI}.
	 */
	function tokenURI(uint256 tokenId) public view override returns (string memory) {
		return lootURI(tokenId, Items.WEAPON);
	}
}
